// Mock Users
export const mockUsers = [
    {
        id: 'citizen-1',
        name: 'Ananya Sharma',
        email: 'ananya.sharma@email.com',
        role: 'citizen',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ananya',
        phone: '+91 98765 43210',
        verified: true,
        createdAt: '2024-01-15',
    },
    {
        id: 'citizen-2',
        name: 'Rajesh Kumar',
        email: 'rajesh.kumar@email.com',
        role: 'citizen',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rajesh',
        phone: '+91 98765 43211',
        verified: true,
        createdAt: '2024-02-20',
    },
    {
        id: 'lawyer-1',
        name: 'Adv. Priya Mehta',
        email: 'priya.mehta@lawfirm.com',
        role: 'lawyer',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya',
        phone: '+91 98765 43212',
        verified: true,
        barNumber: 'MH/12345/2018',
        specialization: ['Civil Law', 'Property Disputes'],
        experience: 6,
        createdAt: '2023-06-10',
    },
    {
        id: 'lawyer-2',
        name: 'Adv. Vikram Singh',
        email: 'vikram.singh@lawfirm.com',
        role: 'lawyer',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Vikram',
        phone: '+91 98765 43213',
        verified: true,
        barNumber: 'DL/54321/2015',
        specialization: ['Family Law', 'Divorce Cases'],
        experience: 9,
        createdAt: '2023-03-15',
    },
    {
        id: 'lawyer-3',
        name: 'Adv. Neha Gupta',
        email: 'neha.gupta@lawfirm.com',
        role: 'lawyer',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Neha',
        phone: '+91 98765 43214',
        verified: false,
        barNumber: 'KA/67890/2020',
        specialization: ['Criminal Law'],
        experience: 4,
        createdAt: '2024-01-05',
    },
    {
        id: 'judge-1',
        name: 'Hon. Justice R.K. Verma',
        email: 'rk.verma@judiciary.gov.in',
        role: 'judge',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=RKVerma',
        phone: '+91 98765 43215',
        verified: true,
        courtName: 'District Court, Delhi',
        designation: 'District Judge',
        createdAt: '2022-01-01',
    },
    {
        id: 'judge-2',
        name: 'Hon. Justice Meera Patel',
        email: 'meera.patel@judiciary.gov.in',
        role: 'judge',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=MeeraPatel',
        phone: '+91 98765 43216',
        verified: false,
        courtName: 'High Court, Mumbai',
        designation: 'Additional Judge',
        createdAt: '2024-03-01',
    },
    {
        id: 'admin-1',
        name: 'System Administrator',
        email: 'admin@ejustice.gov.in',
        role: 'admin',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Admin',
        verified: true,
        createdAt: '2021-01-01',
    },
    {
        id: 'citizen-3',
        name: 'Suresh Raina',
        email: 'suresh.raina@email.com',
        role: 'citizen',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Suresh',
        phone: '+91 98765 43220',
        verified: true,
        createdAt: '2024-04-10',
    },
];

// Mock Cases
export const mockCases = [
    {
        id: 'CASE-2024-001',
        title: 'Property Boundary Dispute - Sharma vs. Patel',
        type: 'Property',
        status: 'in_hearing',
        urgency: 'high',
        description: 'Dispute regarding property boundary encroachment between two neighboring landowners. The plaintiff claims that the defendant has illegally extended their boundary wall by 3 feet into the plaintiff\'s property.',
        citizenId: 'citizen-1',
        lawyerId: 'lawyer-1',
        judgeId: 'judge-1',
        filedAt: '2024-03-15',
        nextHearing: '2024-12-20',
        aiSummary: {
            facts: 'The plaintiff owns a residential property at Plot No. 45, Green Park Colony. The defendant owns the adjacent Plot No. 46. In March 2024, the defendant constructed a new boundary wall that allegedly encroaches 3 feet into the plaintiff\'s property.',
            legalIssue: 'Whether the defendant has committed encroachment on the plaintiff\'s property by constructing a boundary wall beyond their legal boundary.',
            reliefSought: 'Demolition of the encroaching wall, restoration of original boundary, and compensation of ₹2,00,000 for mental harassment and legal expenses.',
        },
    },
    {
        id: 'CASE-2024-002',
        title: 'Tenant Eviction - Kumar vs. Residential Complex',
        type: 'Civil',
        status: 'pending',
        urgency: 'medium',
        description: 'Unlawful eviction of tenant without proper notice period. The landlord has threatened the tenant to vacate within 15 days without providing the mandatory 3-month notice.',
        citizenId: 'citizen-2',
        lawyerId: null,
        judgeId: null,
        filedAt: '2024-11-28',
        nextHearing: null,
        aiSummary: {
            facts: 'The tenant has been residing at the rented premises for 5 years. The landlord issued an eviction notice on November 15, 2024, demanding vacation within 15 days, citing personal need for the property.',
            legalIssue: 'Whether the eviction notice is legally valid under the Rent Control Act, which mandates a 3-month notice period for eviction.',
            reliefSought: 'Stay on eviction, declaration of invalid notice, and protection of tenancy rights.',
        },
    },
    {
        id: 'CASE-2024-003',
        title: 'Divorce Settlement - Confidential',
        type: 'Family',
        status: 'in_hearing',
        urgency: 'medium',
        description: 'Mutual consent divorce with dispute over asset division and child custody arrangements.',
        citizenId: 'citizen-1',
        lawyerId: 'lawyer-2',
        judgeId: 'judge-1',
        filedAt: '2024-09-10',
        nextHearing: '2024-12-18',
        aiSummary: {
            facts: 'Marriage of 8 years with one child aged 6. Both parties have agreed to separation but disagree on division of jointly owned apartment and custody schedule.',
            legalIssue: 'Equitable division of matrimonial assets and determination of custody arrangement in the best interest of the child.',
            reliefSought: 'Divorce decree, fair division of apartment (valued at ₹1.2 Cr), and joint custody with primary residence with mother.',
        },
    },
    {
        id: 'CASE-2024-004',
        title: 'Consumer Complaint - Defective Electronics',
        type: 'Consumer',
        status: 'closed',
        urgency: 'low',
        description: 'Complaint against electronics retailer for selling defective laptop and refusing refund.',
        citizenId: 'citizen-2',
        lawyerId: 'lawyer-1',
        judgeId: 'judge-1',
        filedAt: '2024-05-20',
        nextHearing: null,
        closedAt: '2024-10-15',
        verdict: 'Complaint upheld. Defendant ordered to refund ₹85,000 with 9% interest and ₹15,000 compensation for mental harassment.',
        aiSummary: {
            facts: 'Consumer purchased laptop worth ₹85,000 which developed motherboard issues within 2 months. Retailer refused refund citing software damage (not covered under warranty).',
            legalIssue: 'Whether hardware defect constitutes manufacturing defect entitling consumer to full refund under Consumer Protection Act.',
            reliefSought: 'Full refund of purchase price and compensation for inconvenience.',
        },
    },
    {
        id: 'CASE-2024-005',
        title: 'Workplace Harassment Complaint',
        type: 'Labor',
        status: 'pending',
        urgency: 'high',
        description: 'Complaint of workplace harassment and wrongful termination following complaint to HR.',
        citizenId: 'citizen-1',
        lawyerId: null,
        judgeId: null,
        filedAt: '2024-12-01',
        nextHearing: null,
        aiSummary: {
            facts: 'Employee reported harassment by supervisor to HR on November 1, 2024. Following the complaint, employee faced hostile work environment and was terminated on November 25, 2024, citing "performance issues" without prior warnings.',
            legalIssue: 'Whether termination constitutes retaliation for filing harassment complaint, violating the Sexual Harassment of Women at Workplace Act, 2013.',
            reliefSought: 'Reinstatement, back wages, compensation of ₹10,00,000 for harassment and wrongful termination, and action against perpetrators.',
        },
    },
];

// Mock Documents
export const mockDocuments = [
    {
        id: 'doc-1',
        caseId: 'CASE-2024-001',
        name: 'Property Registration Certificate',
        type: 'pdf',
        size: '2.4 MB',
        uploadedBy: 'citizen-1',
        uploadedAt: '2024-03-15',
        hash: '0x7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d',
        verified: true,
    },
    {
        id: 'doc-2',
        caseId: 'CASE-2024-001',
        name: 'Survey Map with Measurements',
        type: 'pdf',
        size: '5.1 MB',
        uploadedBy: 'lawyer-1',
        uploadedAt: '2024-03-20',
        hash: '0x1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d',
        verified: true,
    },
    {
        id: 'doc-3',
        caseId: 'CASE-2024-001',
        name: 'Photographs of Encroachment',
        type: 'image',
        size: '8.7 MB',
        uploadedBy: 'citizen-1',
        uploadedAt: '2024-03-16',
        hash: '0x2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e',
        verified: true,
    },
    {
        id: 'doc-4',
        caseId: 'CASE-2024-002',
        name: 'Rental Agreement',
        type: 'pdf',
        size: '1.2 MB',
        uploadedBy: 'citizen-2',
        uploadedAt: '2024-11-28',
        hash: '0x3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f',
        verified: true,
    },
    {
        id: 'doc-5',
        caseId: 'CASE-2024-002',
        name: 'Eviction Notice',
        type: 'pdf',
        size: '0.5 MB',
        uploadedBy: 'citizen-2',
        uploadedAt: '2024-11-28',
        hash: '0x4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a',
        verified: false,
    },
];

// Mock Hearings
export const mockHearings = [
    {
        id: 'hearing-1',
        caseId: 'CASE-2024-001',
        date: '2024-12-20',
        time: '10:30 AM',
        type: 'Arguments',
        status: 'scheduled',
        judgeId: 'judge-1',
        courtRoom: 'Court Room 5',
        notes: 'Final arguments from both parties. Plaintiff to present survey evidence.',
        participants: ['citizen-1', 'lawyer-1', 'judge-1'],
    },
    {
        id: 'hearing-2',
        caseId: 'CASE-2024-003',
        date: '2024-12-18',
        time: '02:00 PM',
        type: 'Mediation',
        status: 'scheduled',
        judgeId: 'judge-1',
        courtRoom: 'Mediation Room 2',
        notes: 'Custody arrangement discussion. Child welfare officer to be present.',
        participants: ['citizen-1', 'lawyer-2', 'judge-1'],
    },
    {
        id: 'hearing-3',
        caseId: 'CASE-2024-001',
        date: '2024-11-15',
        time: '11:00 AM',
        type: 'Evidence Review',
        status: 'completed',
        judgeId: 'judge-1',
        courtRoom: 'Court Room 5',
        notes: 'Survey reports examined. Both parties presented photographic evidence.',
        transcript: 'Court proceedings commenced at 11:00 AM. Plaintiff presented survey report dated March 18, 2024. Defendant objected to the methodology. Court admitted the evidence subject to cross-examination...',
        participants: ['citizen-1', 'lawyer-1', 'judge-1'],
    },
    {
        id: 'hearing-4',
        caseId: 'CASE-2024-004',
        date: '2024-10-10',
        time: '03:00 PM',
        type: 'Final Verdict',
        status: 'completed',
        judgeId: 'judge-1',
        courtRoom: 'Court Room 3',
        notes: 'Verdict delivered in favor of complainant.',
        participants: ['citizen-2', 'lawyer-1', 'judge-1'],
    },
];

// Mock Lawyer Requests
export const mockLawyerRequests = [
    {
        id: 'req-1',
        caseId: 'CASE-2024-002',
        lawyerId: 'lawyer-1',
        status: 'pending',
        message: 'I specialize in tenant rights and have handled 50+ similar cases. I can help protect your tenancy rights and ensure proper legal procedure is followed.',
        requestedAt: '2024-11-29',
    },
    {
        id: 'req-2',
        caseId: 'CASE-2024-005',
        lawyerId: 'lawyer-2',
        status: 'pending',
        message: 'With 9 years of experience in labor law and workplace harassment cases, I am well-equipped to handle this matter. I have successfully represented clients in similar retaliation cases.',
        requestedAt: '2024-12-02',
    },
    {
        id: 'req-3',
        caseId: 'CASE-2024-002',
        lawyerId: 'lawyer-2',
        status: 'pending',
        message: 'I have extensive experience in civil matters including tenant disputes. Happy to provide a free initial consultation.',
        requestedAt: '2024-11-30',
    },
];

// Mock Notifications
export const mockNotifications = [
    {
        id: 'notif-1',
        userId: 'citizen-1',
        title: 'Upcoming Hearing',
        message: 'Your hearing for CASE-2024-001 is scheduled for December 20, 2024 at 10:30 AM.',
        type: 'hearing',
        read: false,
        createdAt: '2024-12-15',
    },
    {
        id: 'notif-2',
        userId: 'citizen-1',
        title: 'Lawyer Request',
        message: 'Adv. Priya Mehta has requested to represent you in CASE-2024-002.',
        type: 'lawyer_request',
        read: false,
        createdAt: '2024-11-29',
    },
    {
        id: 'notif-3',
        userId: 'citizen-1',
        title: 'Document Verified',
        message: 'Your uploaded document "Property Registration Certificate" has been verified.',
        type: 'document',
        read: true,
        createdAt: '2024-03-16',
    },
    {
        id: 'notif-4',
        userId: 'lawyer-1',
        title: 'New Case Available',
        message: 'A new property dispute case matching your expertise is available for representation.',
        type: 'case',
        read: false,
        createdAt: '2024-12-01',
    },
    {
        id: 'notif-5',
        userId: 'judge-1',
        title: 'High Priority Case',
        message: 'A new high urgency workplace harassment case requires immediate scheduling.',
        type: 'case',
        read: false,
        createdAt: '2024-12-02',
    },
];

// Mock System Logs
export const mockSystemLogs = [
    {
        id: 'log-1',
        userId: 'citizen-1',
        userName: 'Ananya Sharma',
        action: 'Case Filed',
        details: 'Filed new case CASE-2024-005',
        timestamp: '2024-12-01 14:30:00',
        type: 'case',
    },
    {
        id: 'log-2',
        userId: 'lawyer-1',
        userName: 'Adv. Priya Mehta',
        action: 'Document Uploaded',
        details: 'Uploaded survey report for CASE-2024-001',
        timestamp: '2024-12-01 10:15:00',
        type: 'document',
    },
    {
        id: 'log-3',
        userId: 'admin-1',
        userName: 'System Administrator',
        action: 'User Verified',
        details: 'Verified lawyer account for Adv. Vikram Singh',
        timestamp: '2024-11-30 16:45:00',
        type: 'user',
    },
    {
        id: 'log-4',
        userId: 'judge-1',
        userName: 'Hon. Justice R.K. Verma',
        action: 'Hearing Scheduled',
        details: 'Scheduled hearing for CASE-2024-001 on Dec 20',
        timestamp: '2024-11-28 11:00:00',
        type: 'hearing',
    },
    {
        id: 'log-5',
        userId: 'citizen-2',
        userName: 'Rajesh Kumar',
        action: 'Login',
        details: 'User logged in from New Delhi',
        timestamp: '2024-12-02 09:00:00',
        type: 'auth',
    },
];
